version: '3.7'

services:

  #PHP
  app-php:
    image: app-php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: app-php
    restart: unless-stopped
    working_dir: /var/www/
    networks:
      - app-fp-network
    volumes:
      - ./:/var/www
    depends_on:
      - app-db

  #DB
  app-db:
    image: mariadb:10.4.13
    container_name: app-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: database_name
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_PASSWORD: fp_pass
      MYSQL_USER: fp_user
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - app-fp-network

  #HTTP
  app-nginx:
    image: nginx:latest
    container_name: app-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-fp-network
    depends_on:
      - app-php

networks:
  app-fp-network:
    driver: bridge
